TimeTracer/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import home
from events.views import events, week, day, new_event, generate_description, move_event
from event_editor.views import edit_event

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),

    path('users/', include('users.urls', namespace='users')),

    # Маршрут для отображения календаря по умолчанию

    path('events/', events, {'view_type': 'month'}, name='events'),
    path('events/week/', week, name='week'),
    path('events/day/', day, name='day'),
    path('events/new_event/', new_event, name='new_event'),
    path('events/generate_description/', generate_description, name='generate_description'),
    path('events/day/<int:selected_year>/<int:selected_month>/<int:selected_day>/', day, name='day_selected_day'),

    # Дополнительные маршруты для обработки различных действий или типов отображения

    path('events/week/<int:selected_year>/<int:selected_month>/<int:select_week>/', week, name='week_calendar_selected_week'),
    path('event/<int:event_id>/edit/', edit_event, name='edit_event'),
    path('move_event/', move_event, name='move_event'),

]

events/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('week/', views.week, name='week'),
    path('day/', views.day, name='day'),
    path('', views.events, {'view_type': view_type}, name='events'),
    path('new_event/', views.new_event, name='new_event'),
    path('generate_description/', views.generate_description, name='generate_description'),

]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views
app_name = 'users'

urlpatterns = [
    path('login1/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
]

events/models.py
from django.db import models
from django.contrib.auth.models import User


class Event(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='events_created')
    name = models.CharField(max_length=50, verbose_name='Имя')
    date_start = models.DateField(verbose_name='Дата начала события')
    time_start = models.TimeField(verbose_name='Время начала события', blank=True)
    date_finish = models.DateField(verbose_name='Дата окончания события', blank=True, null=True)
    time_finish = models.TimeField(verbose_name='Время окончания события', blank=True)
    description = models.TextField(max_length=5000, verbose_name='Описание', blank=True)
    color = models.CharField(max_length=10, verbose_name='Цвет')

    class Meta:
        verbose_name = "Event"
        verbose_name_plural = "Events"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.time_start:
            self.time_start = '00:00:00'
        if self.date_start and not self.date_finish:
            self.date_finish = self.date_start
        if self.time_start and not self.time_finish:
            self.time_finish = self.time_start
        super().save(*args, **kwargs)



class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='notifications', blank=True)
    text = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Notification"
        ordering = ['-created_at']

events/forms.py
from django import forms
from events.models import Event

class EventForm(forms.ModelForm):
    PERIODICITY_CHOICES = [
        ('no repeat', 'Не повторять'),
        ('daily', 'Дневная'),
        ('weekly', 'Недельная'),
        ('monthly', 'Месячная'),
        ('yearly', 'Годовая'),
    ]

    periodicity = forms.ChoiceField(
        choices=PERIODICITY_CHOICES,
        required=True,
        label='Периодичность'
    )

    end_date = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={'type': 'date'}),
        label='Конечная дата'
    )

    class Meta:
        model = Event
        fields = ['name', 'date_start', 'time_start', 'date_finish', 'time_finish', 'description', 'color',
                  'periodicity', 'end_date']
        widgets = {
            'date_start': forms.DateInput(attrs={'type': 'date'}),
            'time_start': forms.TimeInput(format='%H:%M', attrs={'type': 'time'}),
            'date_finish': forms.DateInput(attrs={'type': 'date'}),
            'time_finish': forms.TimeInput(format='%H:%M', attrs={'type': 'time'}),
            'color': forms.TextInput(attrs={'type': 'color'}),
            'end_date': forms.DateInput(attrs={'type': 'date'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        periodicity = cleaned_data.get('periodicity')
        end_date = cleaned_data.get('end_date')

        if periodicity != 'no repeat' and not end_date:
            self.add_error('end_date', 'Это поле обязательно для выбранной периодичности.')

        return cleaned_data


TYPES = (
    ('month', 'month'),
    ('week', 'week'),
    ('day', 'day')
)
WEEKS = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
)
MONTHS = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('6', '6'),
    ('7', '7'),
    ('8', '8'),
    ('9', '9'),
    ('10', '10'),
    ('11', '11'),
    ('12', '12')
)
YEARS = (
    ('1', '2015'),
    ('2', '2016'),
    ('3', '2017'),
    ('4', '2018'),
    ('5', '2019'),
    ('6', '2020'),
    ('7', '2021'),
    ('8', '2022'),
    ('9', '2023'),
    ('10', '2024'),
    ('11', '2025'),
    ('12', '2026'),
    ('13', '2027'),
    ('14', '2028'),
    ('15', '2029'),
    ('16', '2030')
)


class ViewTypeForm(forms.Form):
    type = forms.ChoiceField(choices=TYPES)


class DateSelectionForm(forms.Form):
    selected_date = forms.DateField(label='', widget=forms.SelectDateWidget())


class WeekNumberForm(forms.Form):
    number_of_week = forms.ChoiceField(choices=WEEKS)


class MonthSelect(forms.Form):
    selected_month = forms.ChoiceField(choices=MONTHS)


class YearSelect(forms.Form):
    selected_year = forms.ChoiceField(choices=YEARS)


class DayView(forms.Form):
    day_select_form = forms.DateTimeField()
    widget = forms.DateInput(
        attrs={
            'class': 'form_control',
            'type': 'date'
        }
    )

events/views.py
# views.py
from django.shortcuts import render, redirect
from .forms import EventForm, DateSelectionForm
from .models import Event as Event
from .models import Notification
from django.utils import timezone
from datetime import datetime, timedelta
from django.http import JsonResponse
from calendar import monthrange
from django.views.decorators.csrf import csrf_exempt, csrf_protect

from langchain.schema import HumanMessage, SystemMessage
from langchain.chat_models.gigachat import GigaChat

# Авторизация в сервисе GigaChat
auth = 'OWRjNWE4YjgtYmNiZC00YTNlLThmM2EtMzM3ODQxZmM0ODY0Ojk5M2RmY2E4LWI4ZDEtNGI4Yi05ZmQ1LWU3NzBkMGNhYWQ3OQ=='
chat = GigaChat(credentials=auth, verify_ssl_certs=False)

messages = [
    SystemMessage(
        content='Помогите пользователю написать краткое описание события на основе его названия.'
    )
]


def week_view(request, select_week, selected_month, selected_year):
    """
        Функция представления для недельного отображения событий.

        Args:
            request (HttpRequest): Объект HTTP-запроса.
            select_week (int): Выбранный номер недели.
            selected_month (int): Выбранный номер месяца.
            selected_year (int): Выбранный номер года.

        Returns:
            Dict[str, Any]: Словарь, содержащий контекстные данные для недельного отображения.
        """
    form = EventForm()
    if request.method == 'GET':
        # Проверка на передачу года, месяца и недели
        selected_month = int(request.GET.get('selected_month', selected_month))
        selected_year = int(request.GET.get('selected_year', selected_year))
        selected_week = int(request.GET.get('select_week', select_week))
    else:
        selected_month = int(selected_month)
        selected_year = int(selected_year)
        selected_week = int(select_week)

    first_weekday, num_days = monthrange(selected_year, selected_month)
    num_padding_days = (first_weekday) % 7
    days_of_month = []
    week_of_month = []
    for i in range(num_padding_days):
        week_of_month.append(None)
    for day_of_month in range(1, num_days + 1):
        week_of_month.append(datetime(selected_year, selected_month, day_of_month))
        if len(week_of_month) == 7:
            days_of_month.append(week_of_month)
            week_of_month = []
    if week_of_month:
        while len(week_of_month) < 7:
            week_of_month.append(None)
        days_of_month.append(week_of_month)

    current_week = days_of_month[int(selected_week) - 1] if 1 <= int(selected_week) <= len(days_of_month) else \
        days_of_month[0]
    week_counter = len(days_of_month)
    options = [{'value': f'{number + 1}', 'label': f'{number + 1}'} for number in range(week_counter)]

    hours_str = ['00:00'] + [f'{hour:02d}:00' for hour in range(1, 24)]
    hours = [datetime.strptime(hour, '%H:%M') for hour in hours_str]

    notification = Notification.objects.filter(user=request.user)
    events = Event.objects.filter(
        date_start__year=selected_year,
        date_start__month=selected_month,
        user=request.user
    )

    month = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август',
             'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь']
    current_year = timezone.now().year
    current_month = timezone.now().month

    context = {
        'selected_month': month[selected_month - 1], 'form': form, 'events': events,
        'selected_year': selected_year, 'hours': hours,
        'days_of_month': days_of_month, 'current_week': current_week,
        'options': options, 'select_week': selected_week, 'current_month': month[current_month - 1],
        'notification': notification, 'current_year': current_year, 'month': selected_month
    }

    return context


def events(request, view_type='month'):
    """
        Представление для отображения событий в месячном виде. Реализовано добавление и редактирование событий.
        Реализовано изменение даты события с помощью перетаскивания. Добавлены уведомления в качестве напоминий о
        предстоящем событии. Также реализован выбор типа отображения календаря.

        Args:
            request (HttpRequest): Объект HTTP-запроса.
            view_type (str, optional): Тип представления (month, week, day). По умолчанию 'month'.

        Returns:
            HttpResponse: HTTP-ответ с отображением событий.
        """
    user_events = Event.objects.filter(user=request.user)

    for event in user_events:

        date_start_datetime = datetime.combine(event.date_start, event.time_start)
        now_with_timezone = timezone.localtime(timezone.now())
        date_start_aware = date_start_datetime.replace(tzinfo=timezone.utc)
        time_difference = date_start_aware - now_with_timezone

        if time_difference <= timedelta(hours=1) and time_difference.total_seconds() > 0:
            if not Notification.objects.filter(user=request.user, event=event).exists():
                notification_time = event.date_start - timedelta(hours=1)
                notification = Notification(user=request.user, text=f'Время начала события "{event.name}" через час',
                                            created_at=notification_time, event=event)
                notification.save()

    def month_view():
        """
                Отображение месяца.

                Returns:
                    Dict[str, Any]: Словарь, содержащий контекстные данные для отображения месяца.
                """
        form = EventForm()
        current_year = timezone.now().year
        current_month = timezone.now().month

        selected_month = int(request.GET.get('selected_month', current_month))
        selected_year = int(request.GET.get('selected_year', current_year))

        first_weekday, num_days = monthrange(selected_year, selected_month)

        num_padding_days = (first_weekday) % 7
        days_of_month = []
        week = []
        for i in range(num_padding_days):
            week.append(None)
        for day in range(1, num_days + 1):
            week.append(datetime(selected_year, selected_month, day))
            if len(week) == 7:
                days_of_month.append(week)
                week = []
        if week:
            while len(week) < 7:
                week.append(None)
            days_of_month.append(week)

        events = Event.objects.filter(date_start__year=selected_year, date_start__month=selected_month,
                                      user=request.user)
        notification = Notification.objects.filter(user=request.user)
        month = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август',
                 'Сентябрь', 'Август', 'Ноябрь', 'Декабрь']

        context = {'form': form, 'events': events, 'current_month': month[current_month - 1],
                   'current_year': current_year, 'selected_year': selected_year,
                   'days_of_month': days_of_month, 'selected_month': month[selected_month - 1],
                   'notification': notification, 'month': selected_month}
        return context

    description_event = ''
    if 'exit' in request.GET:
        return redirect('users:logout')

    elif 'new_event' in request.GET:
        return redirect('/events/new_event')

    if request.method == 'POST':
        if 'my_button' in request.POST:
            return redirect('home')
        elif 'delete_event_id' in request.POST:  # Проверяем, было ли отправлено сообщение об удалении
            event_id = request.POST.get('delete_event_id')
            event = Event.objects.get(id=event_id)
            event.delete()  # Удаляем событие
            return redirect('/events')  # Перенаправляем обратно на страницу событий после удаления

        elif 'new_event' in request.GET:
            return redirect('/new_event')

    # else для method GET
    else:
        view_type = request.GET.get('view_type', view_type)
        if view_type == 'week':
            return redirect('week')
        elif view_type == 'day':
            return redirect('day')
        elif view_type == 'month':
            calendar_data = month_view()
            template_name = 'events/events.html'
        else:
            return render(request, 'events/error.html', {'message': 'Неизвестный тип отображения'})
        return render(request, template_name, calendar_data)
    form = EventForm()

    current_year = timezone.now().year
    current_month = timezone.now().month

    selected_month = int(request.GET.get('selected_month', current_month))
    selected_year = int(request.GET.get('selected_year', current_year))

    first_weekday, num_days = monthrange(selected_year, selected_month)

    num_padding_days = (first_weekday) % 7
    days_of_month = []
    week = []
    for i in range(num_padding_days):
        week.append(None)
    for day in range(1, num_days + 1):
        week.append(datetime(selected_year, selected_month, day))
        if len(week) == 7:
            days_of_month.append(week)
            week = []
    if week:
        while len(week) < 7:
            week.append(None)
        days_of_month.append(week)

    events = Event.objects.filter(date_start__year=selected_year, date_start__month=selected_month, user=request.user)
    notification = Notification.objects.filter(user=request.user)
    month = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август',
             'Сентябрь', 'Август', 'Ноябрь', 'Декабрь']
    context = {'form': form, 'events': events, 'current_month': month[current_month - 1],
               'current_year': current_year, 'selected_month': month[selected_month - 1],
               'selected_year': selected_year,
               'days_of_month': days_of_month, 'notification': notification, 'month': selected_month}
    return render(request, 'events/events.html', context)


def week(request, selected_month=None, selected_year=None, select_week=None):
    """

events/templates/events/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>sadlkfhlksdlkajf;lasj;lf error</title>
</head>
<body>

</body>
</html>

events/templates/events/new_event.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добавить событие</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <style>
        @font-face {
            font-family: 'IBMPlexSans-Medium';
            src: url('/static/events/css/IBMPlexSans-Medium.ttf') format('truetype');
            font-weight: normal;
            font-style: normal;
        }
        body {
            background-color: #2F303A;
        }
        button {
            background-color: #3A3C42;
            border: none;
            margin: 10px;
            height: 45px;
            width: 120px;
            border-radius: 10px;
            cursor: pointer;
            color: white;
        }
        /*основной блок*/
        .edit {
            background-color: #555769;
            color: #FFF;
            padding: 20px 90px;
            width: 350px;
            border-radius: 50px;
            position: absolute;
            margin-left: 490px;
            margin-top: 20px;
            height:650px;
        }
        label {
            float: left;
            margin-right: 5px;
            height: 30px;
            color: white;
        }
        select, input[type="date"], input[type="time"]  {
            margin-bottom: 10px;
            border-radius: 10px;
            width: 120px;
            padding-left:5px;

        }
        input[type="color"]{
            border-radius:10px;
            width:50px;
            margin-bottom:10px;
            height:25px;
        }
        input[type="text"] {
            border-radius: 10px;
            height: 20px;
            margin-bottom: 12px;
            padding-left: 5px;
            border: none;
        }
        h2 {
            margin-left:130px;
            color: #1E1E1F;
            margin-top: -10px;
        }
        h3 {
            color: white;
        }
        /*2 штучки для всплывающего окна с описанием ИИ*/
        .modal {
            display: none;
            position: fixed;
            z-index: 1;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            overflow: auto;
            background-color: rgb(0,0,0);
            background-color: rgba(0,0,0,0.4);
            padding-top: 60px;
        }
        .modal-content {
            background-color: #fefefe;
            margin: 5% auto;
            padding: 20px;
            border: 1px solid #888;
            width: 60%;
            border-radius: 10px;
        }
        textarea{
            border-radius:15px;
            height:100px;
            width:250px;
        }
    </style>
</head>
<body>
    <div class="edit">
        <img hspace="130px" src="{% static 'events/img/image_2024-04-29_11-20-12.png' %}" alt="pict" width="110px">
        <h2>TimeTracer</h2>
        <h3>Добавить событие:</h3>
        <form id="event-form" method="POST">
            {% csrf_token %}
            <label for="id_name">Название:</label>
            {{ form.name }}
            <br>
            <label for="id_date_start">Дата начала:</label>
            <input type="date" id="id_date_start" name="date_start">
            <br>
            <label for="id_time_start">Время начала:</label>
            <input type="time" id="id_time_start" name="time_start">
            <br>
            <label for="id_date_finish">Дата окончания:</label>
            <input type="date" id="id_date_finish" name="date_finish">
            <br>
            <label for="id_time_finish">Время окончания:</label>
            <input type="time" id="id_time_finish" name="time_finish">
            <br>
            <label for="id_color">Цвет:</label>
            <input type="color" id="id_color" name="color">
            <br>
            <label for="id_periodicity">Повторения:</label>
            {{ form.periodicity }}
            <br>
            <label style="margin-left:-91px;" for="id_end_date">Окончание повторений:</label>
            <input type="date" id="id_end_date" name="end_date">
            <br>
            <label for="id_description">Описание:</label>
            {{ form.description }}
            <br>
            <button type="button" id="generate-description-button" name="description">Добавить описание ИИ</button>
            <button type="submit" name="save_button">Добавить событие</button>
        </form>
    </div>
    <!--плашечка для описания ИИ-->
    <div id="description-modal" class="modal">
        <div class="modal-content">
            <h4>Предложенное описание:</h4>
            <p id="generated-description"></p>
            <div class="modal-buttons">
                <button type="button" id="accept-description-button">Согласиться</button>
                <button type="button" id="reject-description-button">Отказаться</button>
            </div>
        </div>
    </div>
    <!--Для появления плашечки и сбора информации от гигачата-->
    <script>
        $(document).ready(function() {
            const modal = $('#description-modal');

            $('#generate-description-button').click(function() {
                const eventName = $('#id_name').val();
                if (eventName) {
                    $.ajax({
                        type: 'POST',
                        url: '{% url "generate_description" %}',
                        data: {
                            'name': eventName,
                            'csrfmiddlewaretoken': '{{ csrf_token }}'
                        },
                        success: function(response) {
                            $('#generated-description').text(response.description);
                            modal.show();
                        },
                        error: function(xhr, status, error) {
                            alert('Ошибка при генерации описания');
                        }
                    });
                } else {
                    alert('Пожалуйста, введите название события.');
                }
            });

            $('#reject-description-button').click(function() {
                modal.hide();
            });

            $(window).click(function(event) {
                if (event.target.id === 'description-modal') {
                    modal.hide();
                }
            });

            $('#accept-description-button').click(function() {
                const generatedDescription = $('#generated-description').text();
                $('textarea[name="description"]').val(generatedDescription);
                modal.hide();
            });
        });
    </script>
</body>
</html>